2025-07-22 13:14:44,997 - INFO - User 'Skyler' (Role: super_user) logged in.
2025-07-22 13:15:40,398 - INFO - User 'Marty' (Role: kiosk_management) logged in.
2025-07-22 13:15:56,757 - INFO - User 'Skyler' (Role: super_user) logged in.
2025-07-22 13:16:48,306 - INFO - User 'Marty' (Role: kiosk_management) logged in.
2025-07-22 13:19:17,199 - INFO - User 'Skyler' (Role: super_user) logged in.
2025-07-22 13:20:06,244 - INFO - User 'system' (Role: system) logged in.
2025-07-22 14:25:49,978 - ERROR - Klipper fetch for 'Ender 3 Neo #3': 503 Server Error: Klippy Disconnected for url: http://neo3.local/printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard
2025-07-22 14:25:49,995 - ERROR - Klipper fetch for 'Ender 3 Neo #3': 503 Server Error: Klippy Disconnected for url: http://neo3.local/printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard
2025-07-22 14:34:41,367 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x765e35845b80>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:34:55,052 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x765e3582d970>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:34:55,056 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x765e35844b90>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:34:58,005 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x765e358476b0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:35:17,398 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x765e3582da60>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:35:25,050 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x765e35847950>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:35:25,055 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x765e35846120>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:35:34,005 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x765e3582d340>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:35:53,358 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x765e36a0cd40>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:35:55,055 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x765e3582c590>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:35:55,058 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x765e3582df70>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:36:25,712 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f93c7e9c0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:36:25,716 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f93c7d0d0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:36:29,367 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f922a04a0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:36:46,010 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f93c7cd70>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:36:55,700 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f93c7f110>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:36:55,702 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f93c7fe60>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:37:05,375 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f922a14f0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:37:22,010 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f93c7f9b0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:37:25,701 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f922a2ba0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:37:25,704 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f922a1be0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:37:41,368 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f93c7f170>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:37:55,978 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f922a35c0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:37:55,981 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f922a1e20>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:37:58,005 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f93c7f080>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:38:17,364 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f922a1c40>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:38:26,385 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f922a0140>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:38:26,389 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f922a2a80>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:38:34,010 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f7f922ba390>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:39:10,013 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e2aa41d30>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:39:11,950 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e2aa43860>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:39:27,326 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290e9730>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:39:27,335 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290e9670>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:39:32,365 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290eaf60>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:39:46,009 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290eb6e0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:39:57,712 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290e8530>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:39:57,715 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ea1e0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:40:08,366 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290eacc0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:40:08,670 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ec7d0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:40:22,034 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290eae40>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:40:27,854 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290e9eb0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:40:27,859 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290e8fb0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:40:44,359 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290e9ee0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:40:57,856 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ea990>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:40:57,862 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290e9e20>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:40:58,009 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290eb4a0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:41:20,375 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290c3ce0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:41:27,862 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290eb8c0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:41:27,865 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ebb90>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:41:34,027 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290c21e0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:41:56,383 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ec080>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:41:57,861 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ef5f0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:41:57,863 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290c3950>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:42:10,011 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ebc20>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:42:27,863 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290effe0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:42:27,866 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ef410>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:42:32,369 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290e94c0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:42:46,017 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ea180>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:42:57,860 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ea630>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:42:57,863 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ebe30>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:43:08,363 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ee810>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:43:22,050 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ecce0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:43:27,874 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290efb30>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:43:27,877 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ed400>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:43:44,374 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290e8f80>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:43:57,863 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ecda0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:43:57,867 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ecbf0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:43:58,026 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ea000>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:44:20,370 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290eeed0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:44:27,868 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290e8c50>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:44:27,873 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290e9d30>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:44:34,011 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ef950>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:44:56,374 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290ebf50>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:44:57,867 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290c2ea0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:44:57,870 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290eddc0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:45:10,021 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290edc40>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:45:27,873 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290efa40>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:45:27,879 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x762e290eebd0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:45:46,015 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7688886f78f0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:45:57,876 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7688886f6b40>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:45:57,889 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7688886f71d0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:46:08,383 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888852f5f0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:46:22,032 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7688886f7c20>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:46:27,886 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888852e0c0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:46:27,890 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888852d430>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:46:44,367 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7688886f6cc0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:46:57,878 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888852fbf0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:46:57,880 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888852c440>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:46:58,022 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7688886f6ea0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:47:20,386 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888855c050>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:47:27,882 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888854ac90>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:47:27,884 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7688886f6ea0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:47:34,014 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888852c650>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:47:56,371 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x768888548b30>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:47:57,879 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888852d1c0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:47:57,883 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888855dee0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:48:10,015 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888855fa40>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:48:28,726 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888855df40>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:48:28,731 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888855df10>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:48:32,365 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888855fd70>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:48:46,023 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x76888855edb0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:49:22,025 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb363e90>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:49:22,995 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36e390>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:49:29,303 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38d7c0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:49:41,370 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38ff20>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:49:58,043 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38d850>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:49:59,309 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38ec00>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:50:17,383 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36e9c0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:50:29,299 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36e900>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:50:34,027 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38dd60>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:50:41,521 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38ca40>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:50:53,378 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38f3e0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:50:59,348 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38c6b0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:51:01,878 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38d490>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:51:10,027 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38fdd0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:51:29,144 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36d310>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:51:29,356 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36f290>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:51:29,367 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3d94c0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:51:46,019 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36e990>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:51:59,364 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3dbfb0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:52:05,381 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36e2a0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:52:29,497 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38ed20>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:52:33,626 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36dc70>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:52:41,392 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3db980>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:52:59,503 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3d9730>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:53:17,378 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3dbbc0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:53:29,665 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3d8aa0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:53:53,374 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36e900>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:53:59,764 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38cc50>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:54:29,384 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38fbf0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:54:30,076 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3dbc80>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:55:00,150 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3d8c20>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:55:05,369 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36dbb0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:55:30,237 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3da0f0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:55:41,377 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3da690>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:56:00,583 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38e390>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:56:17,372 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38ff20>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:56:31,150 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38d820>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:57:01,222 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38d940>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:57:31,311 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36f800>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:58:01,401 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38edb0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:58:31,969 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36da90>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:59:02,050 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38f650>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 14:59:32,129 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36d6d0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:00:02,215 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38c650>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:00:32,299 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb36f5f0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:01:03,127 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38f590>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:01:33,211 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3d8140>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:02:03,300 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38f2f0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:02:33,739 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38e9c0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:03:04,196 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38f680>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:03:34,282 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3d9340>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:04:04,361 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38fd10>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:04:34,439 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38ebd0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:05:05,022 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb3db980>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:05:35,101 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7aafcb38caa0>: Failed to resolve 'tylerpi.local' ([Errno -2] Name or service not known)"))
2025-07-22 15:06:00,190 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7aafcb3d9730>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-07-22 17:15:11,472 - ERROR - Klipper fetch for 'Tyler's printer': HTTPConnectionPool(host='tylerpi.local', port=80): Max retries exceeded with url: /printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7aafcb3cdac0>, 'Connection to tylerpi.local timed out. (connect timeout=5)'))
2025-07-22 17:15:33,956 - ERROR - Klipper fetch for 'Tyler's printer': 502 Server Error: Bad Gateway for url: http://tylerpi.local/printer/objects/query?print_stats&display_status&heater_bed&extruder&virtual_sdcard
2025-07-22 17:18:44,120 - WARNING - Failed login for username: 'skyler'.
2025-07-22 17:18:51,760 - INFO - User 'Skyler' (Role: super_user) logged in.
2025-07-22 17:26:34,234 - WARNING - Failed login for username: 'system'.
2025-07-22 17:26:53,071 - INFO - User 'system' (Role: system) logged in.
2025-07-22 18:54:48,678 - WARNING - Failed login for username: 'kiosktest'.
2025-07-22 18:54:55,896 - WARNING - Failed login for username: 'kiosktest'.
2025-07-22 18:55:04,248 - INFO - User 'system' (Role: system) logged in.
2025-07-22 18:55:26,805 - INFO - User 'kiosk test' (Role: kiosk_management) logged in.
2025-07-22 18:57:07,034 - INFO - User 'system' (Role: system) logged in.
